/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        forum: {
          bg: "#eef3fb",
          surface: "#ffffff",
          panel: "#f8f9fa",
          panelMuted: "#f3f4f5",
          border: "#d8dfe8",
          borderStrong: "#c1c7d3",
          primary: "#005da7",
          primaryDark: "#004883",
          primarySoft: "#d4e3ff",
          primarySurface: "#c1d9fe",
          ink: "#191c1d",
          inkStrong: "#001c39",
          muted: "#485e7e",
          subtle: "#717783",
          nav: "#111827",
          danger: "#ba1a1a",
          dangerSoft: "#ffdad6",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      boxShadow: {
        panel: "0 12px 32px rgba(25, 28, 29, 0.04)",
        lift: "0 8px 24px rgba(0, 93, 167, 0.12)",
        dialog: "0 24px 64px rgba(15, 23, 42, 0.18)",
      },
      borderRadius: {
        panel: "1rem",
        "2.5xl": "1.25rem",
      },
      maxWidth: {
        content: "75rem",
      },
    },
  },
  plugins: [],
};
