/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#f8f9fa",
        foreground: "#191c1d",
        "inverse-surface": "#2e3132",
        "inverse-primary": "#a4c9ff",
        "surface-container": "#edeeef",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1d",
        secondary: "#496080",
        outline: "#717783",
        "on-primary-fixed": "#001c39",
        "on-primary-container": "#fdfcff",
        "on-tertiary-container": "#fffbff",
        "tertiary-container": "#a06900",
        "on-secondary-fixed": "#001c39",
        "surface-container-high": "#e7e8e9",
        tertiary: "#7f5300",
        "on-tertiary-fixed-variant": "#633f00",
        "on-primary": "#ffffff",
        "on-surface": "#191c1d",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#a4c9ff",
        "surface-container-low": "#f3f4f5",
        "surface-tint": "#0060ac",
        "on-surface-variant": "#414751",
        "secondary-fixed-dim": "#b1c8ed",
        "surface-dim": "#d9dadb",
        "secondary-fixed": "#d4e3ff",
        "tertiary-fixed": "#ffddb4",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e1e3e4",
        "primary-container": "#2976c7",
        "on-secondary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "outline-variant": "#c1c7d3",
        "on-tertiary-fixed": "#291800",
        error: "#ba1a1a",
        "secondary-container": "#c1d9fe",
        "on-secondary-container": "#485e7e",
        "surface-container-lowest": "#ffffff",
        primary: "#005da7",
        "on-secondary-fixed-variant": "#314867",
        "on-primary-fixed-variant": "#004883",
        "inverse-on-surface": "#f0f1f2",
        "surface-bright": "#f8f9fa",
        surface: "#f8f9fa",
        "primary-fixed": "#d4e3ff",
        "tertiary-fixed-dim": "#ffb953",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
